name: environment
run-name: Clean up the environment for PR-${{ github.event.pull_request.number }}

on:
  pull_request:
    types:
      - closed

permissions:
  contents: read
  deployments: write

env:
  GH_TOKEN: ${{ github.token }}
  GH_REPO: ${{ github.repository }}
  ENVIRONMENT: ${{ format('pr-{0}', github.event.pull_request.number) }}

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: delete environment
        run: |
          gh api --method DELETE /repos/:owner/:repo/environments/${ENVIRONMENT}
