name: pr

on:
  pull_request:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: packages/*/coverage/
          retention-days: 1

