name: pull_request

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: packages/*/coverage/
          retention-days: 1

