name: push

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - run: |
          jq -n "${__event__}"
        env:
          __event__: ${{ toJson(github.event) }}
      - uses: actions/download-artifact@v4
        with:
          name: coverage
          path: ${{ github.workspace }}/artifacts
          github-token: ${{ github.token }}
