name: workflow_run

on:
  workflow_run:
    workflows:
      - pull_request
    types:
      - completed

permissions:
  contents: read

jobs:
  workflow_run:
    runs-on: ubuntu-latest
    steps:
      - run: |
          jq -n "${__pull_requests__}"
        env:
          __pull_requests__: ${{ toJson(github.event.workflow_run.pull_requests) }}
      - uses: actions/download-artifact@v4
        with:
          name: coverage
          path: ${{ github.workspace }}/artifacts
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}
      - run: ls -alR
