name: workflow_run

on:
  workflow_run:
    workflows:
      - pr
    types:
      - completed

permissions:
  checks: write

jobs:
  workflow_run:
    runs-on: ubuntu-latest
    steps:
      - uses: matijs/check-run-actions/start@HEAD
        id: start
        with:
          name: ${{ github.job }}
      - run: mkdir ${{ github.workspace }}/artifacts
      - uses: actions/download-artifact@v5
        with:
          name: coverage
          path: ${{ github.workspace }}/artifacts
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}
      - run: ls -alR
      - name: find PR
        run: |
          jq -n "${PAYLOAD}"
        env:
          PAYLOAD: ${{ toJson(github.event.workflow_run.pull_requests) }}
      - uses: matijs/check-run-actions/complete@HEAD
        if: ${{ always() }}
        with:
          check-run-id: ${{ steps.start.outputs.check-run-id }}
          conclusion: ${{ job.status }}

